-- phpMyAdmin SQL Dump
-- version 4.1.14
-- http://www.phpmyadmin.net
--
-- Client :  127.0.0.1
-- Généré le :  Dim 08 Janvier 2017 à 19:07
-- Version du serveur :  5.6.17
-- Version de PHP :  5.5.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Base de données :  `infinite_scroll`
--

-- --------------------------------------------------------

--
-- Structure de la table `defi`
--

CREATE TABLE IF NOT EXISTS `defi` (
  `id` int(255) NOT NULL AUTO_INCREMENT,
  `text` text NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=29 ;

--
-- Contenu de la table `defi`
--

INSERT INTO `defi` (`id`, `text`) VALUES
(1, 'Pop-up sriracha ethical YOLO put a bird on it farm-to-table. Af cred forage ugh, 3 wolf moon scenester cray unicorn chicharrones thundercats tofu retro brunch fingerstache narwhal. Deep v austin migas, humblebrag copper mug kale chips banjo leggings retro. Tote bag meditation helvetica, scenester cred roof party portland artisan synth hoodie four dollar toast shabby chic sriracha shoreditch. Intelligentsia vexillologist whatever, fam chambray 90''s kogi. Glossier kombucha forage fanny pack blue bottle, bespoke vape seitan chartreuse humblebrag air plant VHS tattooed artisan occupy. Irony austin vegan DIY, lumbersexual waistcoat swag asymmetrical stumptown migas succulents air plant woke.'),
(2, 'Pop-up sriracha ethical YOLO put a bird on it farm-to-table. Af cred forage ugh, 3 wolf moon scenester cray unicorn chicharrones thundercats tofu retro brunch fingerstache narwhal. Deep v austin migas, humblebrag copper mug kale chips banjo leggings retro. Tote bag meditation helvetica, scenester cred roof party portland artisan synth hoodie four dollar toast shabby chic sriracha shoreditch. Intelligentsia vexillologist whatever, fam chambray 90''s kogi. Glossier kombucha forage fanny pack blue bottle, bespoke vape seitan chartreuse humblebrag air plant VHS tattooed artisan occupy. Irony austin vegan DIY, lumbersexual waistcoat swag asymmetrical stumptown migas succulents air plant woke.'),
(3, 'Pop-up sriracha ethical YOLO put a bird on it farm-to-table. Af cred forage ugh, 3 wolf moon scenester cray unicorn chicharrones thundercats tofu retro brunch fingerstache narwhal. Deep v austin migas, humblebrag copper mug kale chips banjo leggings retro. Tote bag meditation helvetica, scenester cred roof party portland artisan synth hoodie four dollar toast shabby chic sriracha shoreditch. Intelligentsia vexillologist whatever, fam chambray 90''s kogi. Glossier kombucha forage fanny pack blue bottle, bespoke vape seitan chartreuse humblebrag air plant VHS tattooed artisan occupy. Irony austin vegan DIY, lumbersexual waistcoat swag asymmetrical stumptown migas succulents air plant woke.'),
(4, 'Pop-up sriracha ethical YOLO put a bird on it farm-to-table. Af cred forage ugh, 3 wolf moon scenester cray unicorn chicharrones thundercats tofu retro brunch fingerstache narwhal. Deep v austin migas, humblebrag copper mug kale chips banjo leggings retro. Tote bag meditation helvetica, scenester cred roof party portland artisan synth hoodie four dollar toast shabby chic sriracha shoreditch. Intelligentsia vexillologist whatever, fam chambray 90''s kogi. Glossier kombucha forage fanny pack blue bottle, bespoke vape seitan chartreuse humblebrag air plant VHS tattooed artisan occupy. Irony austin vegan DIY, lumbersexual waistcoat swag asymmetrical stumptown migas succulents air plant woke.'),
(5, 'Synth portland blog, man braid microdosing venmo tumeric fingerstache ennui cray hoodie hammock distillery listicle bespoke. Distillery bushwick helvetica, hammock +1 iceland lumbersexual salvia 8-bit letterpress. Disrupt aesthetic pitchfork mustache, locavore knausgaard succulents paleo pickled craft beer waistcoat master cleanse schlitz. Succulents kogi yuccie copper mug tattooed cardigan. Shabby chic crucifix vexillologist echo park freegan mixtape. Green juice twee lyft, kombucha organic PBR&B stumptown mlkshk. Selvage chicharrones seitan photo booth.'),
(6, 'Synth portland blog, man braid microdosing venmo tumeric fingerstache ennui cray hoodie hammock distillery listicle bespoke. Distillery bushwick helvetica, hammock +1 iceland lumbersexual salvia 8-bit letterpress. Disrupt aesthetic pitchfork mustache, locavore knausgaard succulents paleo pickled craft beer waistcoat master cleanse schlitz. Succulents kogi yuccie copper mug tattooed cardigan. Shabby chic crucifix vexillologist echo park freegan mixtape. Green juice twee lyft, kombucha organic PBR&B stumptown mlkshk. Selvage chicharrones seitan photo booth.'),
(7, 'Synth portland blog, man braid microdosing venmo tumeric fingerstache ennui cray hoodie hammock distillery listicle bespoke. Distillery bushwick helvetica, hammock +1 iceland lumbersexual salvia 8-bit letterpress. Disrupt aesthetic pitchfork mustache, locavore knausgaard succulents paleo pickled craft beer waistcoat master cleanse schlitz. Succulents kogi yuccie copper mug tattooed cardigan. Shabby chic crucifix vexillologist echo park freegan mixtape. Green juice twee lyft, kombucha organic PBR&B stumptown mlkshk. Selvage chicharrones seitan photo booth.'),
(8, 'Synth portland blog, man braid microdosing venmo tumeric fingerstache ennui cray hoodie hammock distillery listicle bespoke. Distillery bushwick helvetica, hammock +1 iceland lumbersexual salvia 8-bit letterpress. Disrupt aesthetic pitchfork mustache, locavore knausgaard succulents paleo pickled craft beer waistcoat master cleanse schlitz. Succulents kogi yuccie copper mug tattooed cardigan. Shabby chic crucifix vexillologist echo park freegan mixtape. Green juice twee lyft, kombucha organic PBR&B stumptown mlkshk. Selvage chicharrones seitan photo booth.'),
(9, 'Everyday carry vinyl lo-fi sriracha viral. Photo booth mustache small batch cliche chicharrones hot chicken, activated charcoal letterpress authentic hell of actually cred food truck offal put a bird on it. You probably haven''t heard of them truffaut schlitz, snackwave cronut sriracha pickled. Marfa crucifix brunch celiac, hella woke hexagon trust fund tilde flannel butcher street art church-key lyft. Hoodie live-edge hashtag, sartorial cold-pressed roof party raclette tattooed raw denim trust fund readymade viral synth. Austin kombucha gluten-free vice, man braid pok pok PBR&B 3 wolf moon. Pabst green juice seitan cray.'),
(10, 'Everyday carry vinyl lo-fi sriracha viral. Photo booth mustache small batch cliche chicharrones hot chicken, activated charcoal letterpress authentic hell of actually cred food truck offal put a bird on it. You probably haven''t heard of them truffaut schlitz, snackwave cronut sriracha pickled. Marfa crucifix brunch celiac, hella woke hexagon trust fund tilde flannel butcher street art church-key lyft. Hoodie live-edge hashtag, sartorial cold-pressed roof party raclette tattooed raw denim trust fund readymade viral synth. Austin kombucha gluten-free vice, man braid pok pok PBR&B 3 wolf moon. Pabst green juice seitan cray.'),
(11, 'Single-origin coffee sustainable small batch cronut la croix woke. Gastropub tattooed cronut, drinking vinegar banjo meditation vexillologist whatever put a bird on it blue bottle craft beer thundercats organic affogato aesthetic. DIY swag pickled put a bird on it VHS occupy, bitters fingerstache venmo. Marfa disrupt cornhole, forage migas venmo aesthetic pug lumbersexual jean shorts authentic whatever etsy DIY kombucha. Austin air plant lumbersexual messenger bag. VHS swag schlitz vice umami meditation, man braid hell of. Skateboard direct trade fap retro hammock ethical.'),
(12, 'Single-origin coffee sustainable small batch cronut la croix woke. Gastropub tattooed cronut, drinking vinegar banjo meditation vexillologist whatever put a bird on it blue bottle craft beer thundercats organic affogato aesthetic. DIY swag pickled put a bird on it VHS occupy, bitters fingerstache venmo. Marfa disrupt cornhole, forage migas venmo aesthetic pug lumbersexual jean shorts authentic whatever etsy DIY kombucha. Austin air plant lumbersexual messenger bag. VHS swag schlitz vice umami meditation, man braid hell of. Skateboard direct trade fap retro hammock ethical.'),
(13, 'Pop-up sriracha ethical YOLO put a bird on it farm-to-table. Af cred forage ugh, 3 wolf moon scenester cray unicorn chicharrones thundercats tofu retro brunch fingerstache narwhal. Deep v austin migas, humblebrag copper mug kale chips banjo leggings retro. Tote bag meditation helvetica, scenester cred roof party portland artisan synth hoodie four dollar toast shabby chic sriracha shoreditch. Intelligentsia vexillologist whatever, fam chambray 90''s kogi. Glossier kombucha forage fanny pack blue bottle, bespoke vape seitan chartreuse humblebrag air plant VHS tattooed artisan occupy. Irony austin vegan DIY, lumbersexual waistcoat swag asymmetrical stumptown migas succulents air plant woke.'),
(14, 'Pop-up sriracha ethical YOLO put a bird on it farm-to-table. Af cred forage ugh, 3 wolf moon scenester cray unicorn chicharrones thundercats tofu retro brunch fingerstache narwhal. Deep v austin migas, humblebrag copper mug kale chips banjo leggings retro. Tote bag meditation helvetica, scenester cred roof party portland artisan synth hoodie four dollar toast shabby chic sriracha shoreditch. Intelligentsia vexillologist whatever, fam chambray 90''s kogi. Glossier kombucha forage fanny pack blue bottle, bespoke vape seitan chartreuse humblebrag air plant VHS tattooed artisan occupy. Irony austin vegan DIY, lumbersexual waistcoat swag asymmetrical stumptown migas succulents air plant woke.'),
(15, 'Pop-up sriracha ethical YOLO put a bird on it farm-to-table. Af cred forage ugh, 3 wolf moon scenester cray unicorn chicharrones thundercats tofu retro brunch fingerstache narwhal. Deep v austin migas, humblebrag copper mug kale chips banjo leggings retro. Tote bag meditation helvetica, scenester cred roof party portland artisan synth hoodie four dollar toast shabby chic sriracha shoreditch. Intelligentsia vexillologist whatever, fam chambray 90''s kogi. Glossier kombucha forage fanny pack blue bottle, bespoke vape seitan chartreuse humblebrag air plant VHS tattooed artisan occupy. Irony austin vegan DIY, lumbersexual waistcoat swag asymmetrical stumptown migas succulents air plant woke.'),
(16, 'Pop-up sriracha ethical YOLO put a bird on it farm-to-table. Af cred forage ugh, 3 wolf moon scenester cray unicorn chicharrones thundercats tofu retro brunch fingerstache narwhal. Deep v austin migas, humblebrag copper mug kale chips banjo leggings retro. Tote bag meditation helvetica, scenester cred roof party portland artisan synth hoodie four dollar toast shabby chic sriracha shoreditch. Intelligentsia vexillologist whatever, fam chambray 90''s kogi. Glossier kombucha forage fanny pack blue bottle, bespoke vape seitan chartreuse humblebrag air plant VHS tattooed artisan occupy. Irony austin vegan DIY, lumbersexual waistcoat swag asymmetrical stumptown migas succulents air plant woke.'),
(17, 'Synth portland blog, man braid microdosing venmo tumeric fingerstache ennui cray hoodie hammock distillery listicle bespoke. Distillery bushwick helvetica, hammock +1 iceland lumbersexual salvia 8-bit letterpress. Disrupt aesthetic pitchfork mustache, locavore knausgaard succulents paleo pickled craft beer waistcoat master cleanse schlitz. Succulents kogi yuccie copper mug tattooed cardigan. Shabby chic crucifix vexillologist echo park freegan mixtape. Green juice twee lyft, kombucha organic PBR&B stumptown mlkshk. Selvage chicharrones seitan photo booth.'),
(18, 'Synth portland blog, man braid microdosing venmo tumeric fingerstache ennui cray hoodie hammock distillery listicle bespoke. Distillery bushwick helvetica, hammock +1 iceland lumbersexual salvia 8-bit letterpress. Disrupt aesthetic pitchfork mustache, locavore knausgaard succulents paleo pickled craft beer waistcoat master cleanse schlitz. Succulents kogi yuccie copper mug tattooed cardigan. Shabby chic crucifix vexillologist echo park freegan mixtape. Green juice twee lyft, kombucha organic PBR&B stumptown mlkshk. Selvage chicharrones seitan photo booth.'),
(19, 'Synth portland blog, man braid microdosing venmo tumeric fingerstache ennui cray hoodie hammock distillery listicle bespoke. Distillery bushwick helvetica, hammock +1 iceland lumbersexual salvia 8-bit letterpress. Disrupt aesthetic pitchfork mustache, locavore knausgaard succulents paleo pickled craft beer waistcoat master cleanse schlitz. Succulents kogi yuccie copper mug tattooed cardigan. Shabby chic crucifix vexillologist echo park freegan mixtape. Green juice twee lyft, kombucha organic PBR&B stumptown mlkshk. Selvage chicharrones seitan photo booth.'),
(20, 'Synth portland blog, man braid microdosing venmo tumeric fingerstache ennui cray hoodie hammock distillery listicle bespoke. Distillery bushwick helvetica, hammock +1 iceland lumbersexual salvia 8-bit letterpress. Disrupt aesthetic pitchfork mustache, locavore knausgaard succulents paleo pickled craft beer waistcoat master cleanse schlitz. Succulents kogi yuccie copper mug tattooed cardigan. Shabby chic crucifix vexillologist echo park freegan mixtape. Green juice twee lyft, kombucha organic PBR&B stumptown mlkshk. Selvage chicharrones seitan photo booth.'),
(21, 'Everyday carry vinyl lo-fi sriracha viral. Photo booth mustache small batch cliche chicharrones hot chicken, activated charcoal letterpress authentic hell of actually cred food truck offal put a bird on it. You probably haven''t heard of them truffaut schlitz, snackwave cronut sriracha pickled. Marfa crucifix brunch celiac, hella woke hexagon trust fund tilde flannel butcher street art church-key lyft. Hoodie live-edge hashtag, sartorial cold-pressed roof party raclette tattooed raw denim trust fund readymade viral synth. Austin kombucha gluten-free vice, man braid pok pok PBR&B 3 wolf moon. Pabst green juice seitan cray.'),
(22, 'Everyday carry vinyl lo-fi sriracha viral. Photo booth mustache small batch cliche chicharrones hot chicken, activated charcoal letterpress authentic hell of actually cred food truck offal put a bird on it. You probably haven''t heard of them truffaut schlitz, snackwave cronut sriracha pickled. Marfa crucifix brunch celiac, hella woke hexagon trust fund tilde flannel butcher street art church-key lyft. Hoodie live-edge hashtag, sartorial cold-pressed roof party raclette tattooed raw denim trust fund readymade viral synth. Austin kombucha gluten-free vice, man braid pok pok PBR&B 3 wolf moon. Pabst green juice seitan cray.'),
(23, 'Everyday carry vinyl lo-fi sriracha viral. Photo booth mustache small batch cliche chicharrones hot chicken, activated charcoal letterpress authentic hell of actually cred food truck offal put a bird on it. You probably haven''t heard of them truffaut schlitz, snackwave cronut sriracha pickled. Marfa crucifix brunch celiac, hella woke hexagon trust fund tilde flannel butcher street art church-key lyft. Hoodie live-edge hashtag, sartorial cold-pressed roof party raclette tattooed raw denim trust fund readymade viral synth. Austin kombucha gluten-free vice, man braid pok pok PBR&B 3 wolf moon. Pabst green juice seitan cray.'),
(24, 'Everyday carry vinyl lo-fi sriracha viral. Photo booth mustache small batch cliche chicharrones hot chicken, activated charcoal letterpress authentic hell of actually cred food truck offal put a bird on it. You probably haven''t heard of them truffaut schlitz, snackwave cronut sriracha pickled. Marfa crucifix brunch celiac, hella woke hexagon trust fund tilde flannel butcher street art church-key lyft. Hoodie live-edge hashtag, sartorial cold-pressed roof party raclette tattooed raw denim trust fund readymade viral synth. Austin kombucha gluten-free vice, man braid pok pok PBR&B 3 wolf moon. Pabst green juice seitan cray.'),
(25, 'Single-origin coffee sustainable small batch cronut la croix woke. Gastropub tattooed cronut, drinking vinegar banjo meditation vexillologist whatever put a bird on it blue bottle craft beer thundercats organic affogato aesthetic. DIY swag pickled put a bird on it VHS occupy, bitters fingerstache venmo. Marfa disrupt cornhole, forage migas venmo aesthetic pug lumbersexual jean shorts authentic whatever etsy DIY kombucha. Austin air plant lumbersexual messenger bag. VHS swag schlitz vice umami meditation, man braid hell of. Skateboard direct trade fap retro hammock ethical.'),
(26, 'Single-origin coffee sustainable small batch cronut la croix woke. Gastropub tattooed cronut, drinking vinegar banjo meditation vexillologist whatever put a bird on it blue bottle craft beer thundercats organic affogato aesthetic. DIY swag pickled put a bird on it VHS occupy, bitters fingerstache venmo. Marfa disrupt cornhole, forage migas venmo aesthetic pug lumbersexual jean shorts authentic whatever etsy DIY kombucha. Austin air plant lumbersexual messenger bag. VHS swag schlitz vice umami meditation, man braid hell of. Skateboard direct trade fap retro hammock ethical.'),
(27, 'Single-origin coffee sustainable small batch cronut la croix woke. Gastropub tattooed cronut, drinking vinegar banjo meditation vexillologist whatever put a bird on it blue bottle craft beer thundercats organic affogato aesthetic. DIY swag pickled put a bird on it VHS occupy, bitters fingerstache venmo. Marfa disrupt cornhole, forage migas venmo aesthetic pug lumbersexual jean shorts authentic whatever etsy DIY kombucha. Austin air plant lumbersexual messenger bag. VHS swag schlitz vice umami meditation, man braid hell of. Skateboard direct trade fap retro hammock ethical.'),
(28, 'Single-origin coffee sustainable small batch cronut la croix woke. Gastropub tattooed cronut, drinking vinegar banjo meditation vexillologist whatever put a bird on it blue bottle craft beer thundercats organic affogato aesthetic. DIY swag pickled put a bird on it VHS occupy, bitters fingerstache venmo. Marfa disrupt cornhole, forage migas venmo aesthetic pug lumbersexual jean shorts authentic whatever etsy DIY kombucha. Austin air plant lumbersexual messenger bag. VHS swag schlitz vice umami meditation, man braid hell of. Skateboard direct trade fap retro hammock ethical.');

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
